Repository osism/container-image-osism-ansible, pull requests merged in 2021-05, with the labels that each got.

#142 Add sudo to be able to run local actions
  Containerfile
  files/dragon_sudoers
Labels: Type: Feature

#143 Only remove 99-netbox.yml if /ansible/inventory is writable
  files/scripts/run-ansible.sh
  files/scripts/run-generic.sh
  files/scripts/run-infrastructure.sh
  files/scripts/run-manager.sh
  files/scripts/run-monitoring.sh
  files/scripts/run-openstack.sh
  files/scripts/run-state.sh
  files/scripts/run-without-secrets.sh
  files/scripts/run.sh
Labels: Type: Bugfix

#144 Use the ansible-defaults repository
  Containerfile
Labels: Type: Feature

#145 Revert "Add sudo to be able to run local actions"
  Containerfile
  files/dragon_sudoers
Labels: Type: Feature

#146 Allow manual workflow triggering
  .github/workflows/build-docker-image.yml
Labels: Type: CI
